#:schema node_modules/wrangler/config-schema.json
name = "rikai-api"
main = "src/index.ts"
compatibility_date = "2025-12-30"

# 1. データベース設定 (ステップ2でメモした内容に書き換えてください)
[[d1_databases]]
binding = "rikai_db"
database_name = "rikai-db"
database_id = "85fdfca6-fcbf-43c7-a341-bff3dc776c92"

# 2. 環境変数
[vars]
NODE_ENV = "production"
FRONTEND_URL = "https://0bcbd398.rikai.pages.dev/" # PagesのURLが決まったら書き換える

# 3. ログ・監視設定
[observability]
enabled = true
